## dcdh_table.R
## Builds the de Chaisemartin-D'Haultfoeuille episode table for the paper.
##
## Inputs : Code/replication/exported/dcdh_episodes.csv (from dcdh_episodes.do)
## Outputs: paper/tables/dcdh_episodes.tex
## Run    : Rscript Code/CARES/dcdh_table.R   (after dcdh_episodes.do)

suppressPackageStartupMessages({ library(tidyverse); library(here) })

exp_dir <- here::here("Code", "replication", "exported")
res <- readr::read_csv(file.path(exp_dir, "dcdh_episodes.csv"), show_col_types = FALSE)
stopifnot(!anyNA(res[c("eff1", "se_eff1", "avg", "se_avg", "p_placebo")]))

## Switching states used by the estimator (unweighted, from save_sample).
## The count must be the same for every outcome and spec within an episode.
n_sw <- res %>% group_by(episode) %>%
  summarize(lo = min(n_switch), hi = max(n_switch), .groups = "drop")
stopifnot(all(n_sw$lo == n_sw$hi))
n_sw <- deframe(select(n_sw, episode, lo))

## Stars use normal critical values at the fixest etable thresholds (10/5/1%)
star <- function(b, se) {
  z <- abs(b / se)
  case_when(z > 2.576 ~ "$^{***}$", z > 1.960 ~ "$^{**}$", z > 1.645 ~ "$^{*}$", TRUE ~ "")
}
est <- function(b, se) paste0(sprintf("%0.3f", b), star(b, se))
se  <- function(x) sprintf("(%0.3f)", x)

ep_lab <- c(E1 = "\\textit{A. FPUC-\\$600 onset (2020, benefits on)}",
            E2 = "\\textit{B. LWA onset (2020, benefits on)}",
            E3 = "\\textit{C. FPUC-\\$300 early termination (2021, benefits off)}")
y_lab  <- c(campaigns = "log(campaigns)", donations = "log(donations)",
            amount = "log(amount raised)", finemerg = "log(fin.\\ emergency + 1)",
            business = "log(business + 1)")

wide <- res %>%
  select(episode, outcome, spec, eff1, se_eff1, avg, se_avg, p_placebo) %>%
  pivot_wider(names_from = spec, values_from = c(eff1, se_eff1, avg, se_avg, p_placebo))

body <- character(0)
for (e in names(ep_lab)) {
  body <- c(body, sprintf("\\multicolumn{6}{l}{%s} \\\\", ep_lab[e]))
  for (i in which(wide$episode == e)) {
    r <- wide[i, ]
    body <- c(body,
      sprintf("\\quad %s & %s & %s & %0.2f & %s & %0.2f \\\\", y_lab[r$outcome],
              est(r$eff1_none, r$se_eff1_none), est(r$avg_none, r$se_avg_none),
              r$p_placebo_none, est(r$avg_ctrl, r$se_avg_ctrl), r$p_placebo_ctrl),
      sprintf(" & %s & %s & & %s & \\\\",
              se(r$se_eff1_none), se(r$se_avg_none), se(r$se_avg_ctrl)))
  }
  body <- c(body, sprintf("\\quad Switching states & \\multicolumn{5}{c}{%d} \\\\", n_sw[e]))
  if (e != "E3") body <- c(body, "\\addlinespace")
}

note <- paste(
  "de Chaisemartin and D'Haultf{\\oe}uille (2026) \\texttt{did\\_multiplegt\\_dyn},",
  "estimated separately for each staggered episode of the composite treatment.",
  "Switching states are compared with states whose treatment has not yet changed;",
  "in Panel A the last state to switch (WV) serves only as a comparison.",
  "Weekly state panel, population-weighted, standard errors clustered by state.",
  "The average effect is the switcher-weighted average of the effects in weeks",
  "$\\ell=1$--4 after the switch. Placebo $p$-value: joint test that four pre-switch",
  "placebos equal zero. Columns (1)--(3) omit time-varying controls, as in the clean",
  "specification; columns (4)--(5) add COVID cases, initial and continued claims, the",
  "insured unemployment rate, and PUA initial claims. Panel C treatment is benefit",
  "termination, so a positive sign means more campaigning after benefits end.",
  "$^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$ (normal critical values).")

tex <- c(
  "% Generated by Code/CARES/dcdh_table.R from dcdh_episodes.do",
  "\\begingroup\\centering\\small",
  "\\begin{tabular}{lccccc}", "\\toprule",
  paste(" & \\multicolumn{3}{c}{No time-varying controls}",
        "& \\multicolumn{2}{c}{Baseline controls} \\\\"),
  "\\cmidrule(lr){2-4} \\cmidrule(lr){5-6}",
  " & Effect at & Average & Placebo & Average & Placebo \\\\",
  " & switch & effect & $p$-value & effect & $p$-value \\\\",
  " & (1) & (2) & (3) & (4) & (5) \\\\",
  "\\midrule", body, "\\bottomrule",
  sprintf("\\multicolumn{6}{p{0.95\\textwidth}}{\\footnotesize{%s}}", note),
  "\\end{tabular}\\par\\endgroup")

writeLines(tex, here::here("paper", "tables", "dcdh_episodes.tex"))
message("Saved: paper/tables/dcdh_episodes.tex (switchers: ",
        paste(names(n_sw), n_sw, collapse = ", "), ")")
