## robustness_methods.R
## Alternative-methodology robustness battery for the GoFundMe/UI paper.
## Addresses the audit's central concern (identifying variation vs. headline
## outcome do not overlap in time) and the non-absorbing composite treatment.
##
## Sections:
##   A. Callaway-Sant'Anna (2021) DR DiD on the 2021 FPUC-$300 staggered
##      termination ("benefits off"); selection handled via xformla (1a).
##   B. MatchIt/IPW 2x2 DiD cross-check of A (1a, transparency).
##   C. de Chaisemartin-D'Haultfoeuille did_multiplegt_dyn on the non-absorbing
##      composite treat, extensive margin (2a).
##   D. Program-specific FPUC600/LWA/FPUC300 indicators on counts (2b).
##   E. Treatment-timing selection/balance diagnostic (Tier 2, 4a).
##   F. Randomization inference for the 1a ATT (Tier 2, 4b).
##   G. Honest DiD retry on the termination event study (Tier 2, 3b).
##
## Each section is wrapped in tryCatch so one failure does not abort the run.
## Run:  Rscript Code/CARES/robustness_methods.R   (after build_fpuc300_termination.R)

suppressPackageStartupMessages({
  library(tidyverse); library(here); library(fixest)
  library(did); library(MatchIt)
})
set.seed(20260622)

exp_dir <- here::here("Code", "replication", "exported")
tab_dir <- here::here("paper", "tables")
fig_dir <- here::here("paper", "figures")
dir.create(tab_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(fig_dir, recursive = TRUE, showWarnings = FALSE)

panel_w <- readr::read_csv(file.path(exp_dir, "panel_termination_2021.csv"),
                           show_col_types = FALSE)

## Aggregate weekly -> monthly to reduce sparsity (weekly counts average ~1.75,
## too thin for the CS group-time cells). Termination binned to month: June
## (<= ISO wk 26) vs July+ (wk 27-31); gmonth = 0 for never-early controls.
panel <- panel_w %>%
  mutate(month = pmin(12L, as.integer(ceiling(week / 4.345)))) %>%
  group_by(state, state_id, month, early, term_week) %>%
  summarize(across(c(num_financial_emergency, num_business, campaigns,
                     donationsTotal, amountTotal), sum),
            across(c(median_income, percent_poverty, total_population,
                     insured_unemployment_rate), first), .groups = "drop") %>%
  mutate(gmonth = if_else(early, pmin(12L, as.integer(ceiling(term_week / 4.345))), 0L))

writetab <- function(lines, file) { writeLines(lines, file.path(tab_dir, file))
  cat("      Saved:", file, "\n") }

## ===========================================================================
## A. Callaway-Sant'Anna DiD on 2021 FPUC-$300 termination (monthly, IPW).
##    IPW reweights treated/control via a propensity model on baseline
##    observables -- the requested selection-on-observables handling. DR/reg
##    are numerically unstable here (a near-singleton July cohort), so IPW is
##    the reported estimator.
## ===========================================================================
cat("[A] Callaway-Sant'Anna termination DiD (monthly, IPW)...\n")
cs_results <- list()
run_cs <- function(yname, data = panel, label = yname) {
  att <- att_gt(
    yname = yname, tname = "month", idname = "state_id", gname = "gmonth",
    xformla = ~ percent_poverty + median_income,
    data = as.data.frame(data), control_group = "nevertreated",
    est_method = "ipw"
  )
  list(simple = aggte(att, type = "simple", na.rm = TRUE),
       dynamic = aggte(att, type = "dynamic", na.rm = TRUE),
       att = att)
}
for (yv in c("num_financial_emergency", "campaigns", "amountTotal")) {
  cs_results[[yv]] <- tryCatch(run_cs(yv),
    error = function(e) { cat("      CS", yv, "failed:", conditionMessage(e), "\n"); NULL })
}

## Sensitivity: drop the two states whose panel termination status disagrees
## with the public record (VT flagged early but not in public list; NH the
## reverse). See build_fpuc300_termination.R cross-check.
cs_sens <- tryCatch(run_cs("num_financial_emergency",
                           data = dplyr::filter(panel, !state %in% c("VT","NH"))),
  error = function(e) { cat("      CS sensitivity failed:", conditionMessage(e), "\n"); NULL })

## Build the CS results table
if (!is.null(cs_results[["num_financial_emergency"]])) {
  row1 <- function(r, nm) {
    s <- r$simple
    sprintf("%s & %0.4f & %0.4f & %s \\\\", nm, s$overall.att, s$overall.se,
            ifelse(abs(s$overall.att/s$overall.se) > 1.96, "Yes", "No"))
  }
  cs_lines <- c(
    "% Generated by Code/CARES/robustness_methods.R [A]",
    "\\begingroup\\centering", "\\begin{tabular}{lccc}", "\\toprule",
    "Outcome & ATT & Std. err. & Sig. (5\\%) \\\\", "\\midrule",
    row1(cs_results[["num_financial_emergency"]], "Financial emergency (count)"),
    if (!is.null(cs_results[["campaigns"]])) row1(cs_results[["campaigns"]], "All campaigns (count)"),
    if (!is.null(cs_results[["amountTotal"]])) row1(cs_results[["amountTotal"]], "Total amount raised"),
    if (!is.null(cs_sens)) row1(cs_sens, "Fin. emerg. (excl. VT, NH)"),
    "\\bottomrule",
    "\\multicolumn{4}{l}{\\footnotesize{Callaway-Sant'Anna (2021) ATT, inverse-propensity weighted on baseline poverty}}\\\\",
    "\\multicolumn{4}{l}{\\footnotesize{and median income; never-treated controls; monthly. Treatment = early FPUC-\\$300 termination.}}",
    "\\end{tabular}\\par\\endgroup")
  writetab(cs_lines[!sapply(cs_lines, is.null)], "cs_termination.tex")

  ## Dynamic event-study figure for the headline outcome
  tryCatch({
    pdf(file.path(fig_dir, "cs_event_study.pdf"), width = 12, height = 5, bg = "white")
    print(ggdid(cs_results[["num_financial_emergency"]]$dynamic) +
            ggplot2::ggtitle("Callaway-Sant'Anna: FPUC-$300 Termination and Financial-Emergency Campaigns"))
    dev.off(); cat("      Saved: cs_event_study.pdf\n")
  }, error = function(e) cat("      CS figure failed:", conditionMessage(e), "\n"))

  cat("      CS fin-emerg ATT:",
      round(cs_results[["num_financial_emergency"]]$simple$overall.att, 4),
      "SE", round(cs_results[["num_financial_emergency"]]$simple$overall.se, 4), "\n")
}

## ===========================================================================
## B. IPW-weighted 2x2 DiD cross-check (transparent, robust to the 26>24
##    treated/control imbalance that breaks 1:1 matching). Propensity from a
##    baseline-observables logit; ATT weights; DiD around the June termination.
## ===========================================================================
cat("[B] IPW-weighted DiD cross-check...\n")
tryCatch({
  base_cov <- panel %>% group_by(state, state_id) %>%
    summarize(early = as.integer(first(early)),
              median_income = first(median_income),
              percent_poverty = first(percent_poverty),
              total_population = first(total_population), .groups = "drop")
  ## propensity score for early termination on baseline observables
  ps <- glm(early ~ scale(median_income) + scale(percent_poverty) + scale(total_population),
            family = binomial, data = base_cov)
  base_cov$pscore <- predict(ps, type = "response")
  ## ATT weights: treated = 1, control = p/(1-p)
  base_cov <- base_cov %>%
    mutate(ipw = if_else(early == 1, 1, pscore / pmax(1 - pscore, 1e-3)))
  did_dat <- panel %>%
    left_join(base_cov %>% select(state, early2 = early, ipw), by = "state") %>%
    mutate(post = as.integer(month >= 6), treatpost = early2 * post)
  ## also combine the population weight with the IPW weight
  did_dat$w <- did_dat$ipw * did_dat$total_population
  m_did <- feols(num_financial_emergency ~ post + treatpost | state_id,
                 cluster = ~state_id, weights = ~w, data = did_dat)
  ips <- c("% Generated by Code/CARES/robustness_methods.R [B]",
           "\\begingroup\\centering\\begin{tabular}{lcc}", "\\toprule",
           "Interaction (early $\\times$ post) & Estimate & Std. err. \\\\", "\\midrule",
           sprintf("IPW-weighted DiD (fin. emergency count) & %0.4f & %0.4f \\\\",
                   coef(m_did)["treatpost"], sqrt(diag(vcov(m_did)))["treatpost"]),
           "\\bottomrule",
           "\\multicolumn{3}{l}{\\footnotesize{Inverse-propensity (ATT) weighted on baseline income, poverty, population $\\times$ population weight.}}",
           "\\end{tabular}\\par\\endgroup")
  writetab(ips, "matched_did.tex")
  cat("      IPW DiD interaction:", round(coef(m_did)["treatpost"], 4), "\n")
}, error = function(e) cat("      IPW DiD section failed:", conditionMessage(e), "\n"))

cat("[A/B] done.\n")

## ===========================================================================
## Load full 2020-2021 panels for the switching-treatment and program-specific
## analyses (sections C, D) and the balance/RI diagnostics.
## ===========================================================================
load(here::here(".RData"))
weekLabel <- ungroup(weekLabel); weekCamp <- ungroup(weekCamp)
## continuous week index across 2020-2021 and program indicators
mk_time <- function(df) df %>%
  mutate(yr = as.integer(as.character(year)),
         twave = (yr - 2020L) * 53L + as.integer(week),
         fpuc600 = as.integer((week >= fWeek & week <= fWeek1End) & yr == 2020),
         lwa     = as.integer((week >= lWeekStart & week <= lWeekEnd) & !is.na(lWeekStart) & yr == 2020),
         fpuc300 = as.integer((week >= fWeek2 & week <= fWeek2End) & yr == 2021)) %>%
  mutate(across(c(fpuc600, lwa, fpuc300), ~ replace_na(.x, 0L)))
wL <- mk_time(weekLabel)
wC <- mk_time(weekCamp)
wC$state_id <- as.integer(factor(wC$state))
wL$state_id <- as.integer(factor(wL$state))

## ===========================================================================
## C. de Chaisemartin-D'Haultfoeuille switching-treatment estimator. Correct
##    tool for the NON-ABSORBING composite `treat` (Sun-Abraham/CS assume
##    absorbing adoption). Extensive margin (counts). Dynamic + placebo.
## ===========================================================================
## Implemented in Stata, not here: the R DYN package needs `polars`, which
## will not build on this Windows/R 4.4.2 setup, and DIDmultiplegt's
## did_multiplegt_old returns non-finite estimates on these sparse weekly
## counts. Stata's did_multiplegt_dyn runs episode by episode (FPUC-600 onset,
## LWA onset, FPUC-300 early termination), the only staggered switches in
## `treat`. Paper: sec:dcdh.
##   Stata:  StataMP-64 /e do Code/CARES/dcdh_episodes.do
##   Table:  Rscript Code/CARES/dcdh_table.R  -> paper/tables/dcdh_episodes.tex
cat("[C] de Chaisemartin estimator: run Code/CARES/dcdh_episodes.do (Stata),",
    "then Code/CARES/dcdh_table.R.\n")

## ===========================================================================
## D. Program-specific indicators (FPUC600 / LWA / FPUC300) on counts.
##    Currently the paper only does this for goal amounts (diff4). Extensive
##    margin here. Separates the blended ITF `treat` into its components.
## ===========================================================================
cat("[D] Program-specific indicators on counts...\n")
tryCatch({
  prog <- function(df, yv) feols(
    as.formula(paste0("log(", yv, " + 1) ~ fpuc600 + lwa + fpuc300 + median_income +",
                      "cases + initial_claims + insured_unemployment_rate + continued_claims + puaIC",
                      "| state + year^week")),
    cluster = ~state, weights = ~total_population, data = df)
  p_fe  <- prog(wL, "num_financial_emergency")
  p_biz <- prog(wL, "num_business")
  p_all <- prog(wC, "campaigns")
  etable(list("Fin. Emergency" = p_fe, "Business" = p_biz, "All campaigns" = p_all),
         keep = c("%fpuc600", "%lwa", "%fpuc300"),
         dict = c(fpuc600 = "FPUC-$600", lwa = "LWA", fpuc300 = "FPUC-$300"),
         title = "Program-Specific Effects on Campaign Counts",
         style.tex = style.tex("aer"), fitstat = ~ r2 + n,
         file = file.path(tab_dir, "program_specific.tex"), replace = TRUE)
  cat("      Saved: program_specific.tex (fpuc600 fe coef",
      round(coef(p_fe)["fpuc600"], 4), ")\n")
}, error = function(e) cat("      Program-specific section failed:", conditionMessage(e), "\n"))

## ===========================================================================
## E. Treatment-timing selection / balance diagnostic (Tier 2, 4a).
##    Regress early-termination status and termination week on baseline
##    observables -> characterizes selection-into-treatment.
## ===========================================================================
cat("[E] Treatment-timing balance diagnostic...\n")
tryCatch({
  bc <- panel %>% group_by(state) %>%
    summarize(early = as.integer(first(gmonth > 0)),
              term_week = first(term_week),
              median_income = first(median_income),
              percent_poverty = first(percent_poverty),
              total_population = first(total_population), .groups = "drop")
  bm <- lm(early ~ scale(median_income) + scale(percent_poverty) + scale(total_population), data = bc)
  ct <- summary(bm)$coefficients
  rn <- c("Median income", "Poverty rate", "Population")
  bl <- c("% Generated by Code/CARES/robustness_methods.R [E]",
          "\\begingroup\\centering\\begin{tabular}{lcc}", "\\toprule",
          "Baseline covariate (standardized) & Coef. on Pr(early term.) & Std. err. \\\\", "\\midrule",
          sprintf("%s & %0.4f & %0.4f \\\\", rn, ct[2:4, 1], ct[2:4, 2]),
          "\\bottomrule",
          "\\multicolumn{3}{l}{\\footnotesize{LPM of early FPUC-\\$300 termination on standardized baseline observables.}}",
          "\\end{tabular}\\par\\endgroup")
  writetab(bl, "balance_timing.tex")
  cat("      Balance: poverty coef on Pr(early) =", round(ct[3, 1], 4), "\n")
}, error = function(e) cat("      Balance section failed:", conditionMessage(e), "\n"))

## ===========================================================================
## F. Randomization inference for the 1a ATT (Tier 2, 4b). Permute early-
##    termination assignment across states; recompute the IPW DiD interaction;
##    design-based p-value robust to 50 clusters + switching.
## ===========================================================================
cat("[F] Randomization inference...\n")
tryCatch({
  obs_int <- coef(feols(num_financial_emergency ~ post + treatpost | state_id,
                        weights = ~total_population,
                        data = panel %>% mutate(post = as.integer(month >= 6),
                                                treatpost = as.integer(early) * post)))["treatpost"]
  states <- unique(panel$state); n_early <- n_distinct(panel$state[panel$early])
  B <- 1000; perm <- numeric(B)
  for (b in seq_len(B)) {
    fake_early <- sample(states, n_early)
    d <- panel %>% mutate(e = as.integer(state %in% fake_early),
                          post = as.integer(month >= 6), tp = e * post)
    perm[b] <- coef(feols(num_financial_emergency ~ post + tp | state_id,
                          weights = ~total_population, data = d))["tp"]
  }
  p_ri <- (1 + sum(abs(perm) >= abs(obs_int))) / (B + 1)
  ri <- c("% Generated by Code/CARES/robustness_methods.R [F]",
          "\\begingroup\\centering\\begin{tabular}{lc}", "\\toprule",
          "Quantity & Value \\\\", "\\midrule",
          sprintf("Observed DiD interaction & %0.4f \\\\", obs_int),
          sprintf("Randomization-inference $p$-value & %0.4f \\\\", p_ri),
          sprintf("Permutations & %d \\\\", B),
          "\\bottomrule",
          "\\multicolumn{2}{l}{\\footnotesize{Treatment timing reassigned across states; two-sided design-based $p$.}}",
          "\\end{tabular}\\par\\endgroup")
  writetab(ri, "randinf.tex")
  cat("      RI p-value:", round(p_ri, 4), "\n")
}, error = function(e) cat("      RI section failed:", conditionMessage(e), "\n"))

## ===========================================================================
## G. Honest DiD on the termination event study (Tier 2, 3b). Retry the
##    package with the smaller, balanced termination event window (the FPUC-600
##    event study triggered an internal symmetry failure in the audit).
## ===========================================================================
cat("[G] Honest DiD on termination event study...\n")
tryCatch({
  ## simple fixest event study around June termination, monthly
  es_dat <- panel %>% mutate(rel = month - 6L)            # event time vs June
  es <- feols(num_financial_emergency ~ i(rel, early, ref = -1) | state_id + month,
              cluster = ~state_id, data = es_dat)
  if (requireNamespace("HonestDiD", quietly = TRUE)) {
    terms <- grep("^rel::", names(coef(es)), value = TRUE)
    lags <- as.integer(sub("^rel::(-?[0-9]+):early", "\\1", terms))
    ord <- order(lags); terms <- terms[ord]; lags <- lags[ord]
    bh <- unname(coef(es)[terms]); S <- unname(vcov(es)[terms, terms, drop = FALSE])
    S <- (S + t(S)) / 2
    keep <- !is.na(bh); bh <- bh[keep]; S <- S[keep, keep, drop = FALSE]; lags <- lags[keep]
    hd <- HonestDiD::createSensitivityResults_relativeMagnitudes(
      betahat = bh, sigma = S, numPrePeriods = sum(lags < 0),
      numPostPeriods = sum(lags >= 0), Mbarvec = c(0.5, 1, 1.5, 2))
    ht <- c("% Generated by Code/CARES/robustness_methods.R [G]",
            "\\begingroup\\centering\\begin{tabular}{rrr}", "\\toprule",
            "$\\bar{M}$ & Lower bound & Upper bound \\\\", "\\midrule",
            sprintf("%0.1f & %0.4f & %0.4f \\\\", hd$Mbar, hd$lb, hd$ub),
            "\\bottomrule",
            "\\multicolumn{3}{l}{\\footnotesize{Rambachan-Roth (2023) relative-magnitudes bounds, FPUC-\\$300 termination event study.}}",
            "\\end{tabular}\\par\\endgroup")
    writetab(ht, "honest_did_termination.tex")
    cat("      HonestDiD Mbar=1 bound: [", round(hd$lb[hd$Mbar==1],3), ",", round(hd$ub[hd$Mbar==1],3), "]\n")
  }
}, error = function(e) cat("      HonestDiD section failed:", conditionMessage(e), "\n"))

cat("\n[done] All robustness sections complete.\n")
