## referee2_robustness_fix.R
## Populates the two robustness pieces that were unpopulated in the manuscript:
##   (M2) Wild cluster bootstrap p-values  -> paper/tables/wild_bootstrap.tex
##   (M4) Honest DiD (Rambachan-Roth 2023)  -> paper/tables/honest_did.tex
## and prints the macro values so paper/inline_stats.tex can be updated.
##
## fwildclusterboot is unavailable for R 4.4.2, so the wild cluster bootstrap is
## implemented manually: restricted (null-imposed) Rademacher WCR, clustered on
## state, matching Cameron-Gelbach-Miller (2008). Results are sanity-checked
## against the asymptotic cluster-robust p-values.
##
## Run:  Rscript Code/replication/referee2_robustness_fix.R

suppressPackageStartupMessages({ library(fixest); library(tidyverse); library(here) })

set.seed(20260514)
B <- 2999

load(here::here(".RData"))
weekCamp  <- ungroup(weekCamp)
weekLabel <- ungroup(weekLabel)
tab_dir <- here::here("paper", "tables")

C1 <- c("median_income","percent_poverty","cases","initial_claims",
        "insured_unemployment_rate","continued_claims","puaIC")
C2 <- c("median_income","cases","initial_claims",
        "insured_unemployment_rate","continued_claims","puaIC")

## ---- manual restricted (null-imposed) WCR Rademacher bootstrap -------------
wcr_p <- function(data, yvar, treat = "treat", controls, cluster = "state", B = 2999) {
  d <- data
  d$.y <- d[[yvar]]
  fe <- "state + year^week"
  full_f <- as.formula(paste0(".y ~ ", treat, " + ", paste(controls, collapse=" + "),
                              " | ", fe))
  rest_f <- as.formula(paste0(".y ~ ", paste(controls, collapse=" + "), " | ", fe))
  m_full <- feols(full_f, data = d, weights = ~total_population, cluster = stats::reformulate(cluster))
  t_obs  <- coef(m_full)[treat] / sqrt(diag(vcov(m_full)))[treat]
  m_rest <- feols(rest_f, data = d, weights = ~total_population)
  fit0 <- predict(m_rest); res0 <- resid(m_rest)
  cl   <- d[[cluster]]
  gnames <- unique(cl)
  tstar <- numeric(B)
  for (b in seq_len(B)) {
    w <- sample(c(-1, 1), length(gnames), replace = TRUE)
    names(w) <- gnames
    d$.y <- fit0 + w[as.character(cl)] * res0
    mb <- feols(full_f, data = d, weights = ~total_population,
                cluster = stats::reformulate(cluster))
    tstar[b] <- coef(mb)[treat] / sqrt(diag(vcov(mb)))[treat]
  }
  p_boot  <- (1 + sum(abs(tstar) >= abs(t_obs))) / (B + 1)
  p_asym  <- fixest::pvalue(m_full)[treat]
  list(p_boot = unname(p_boot), p_asym = unname(p_asym), t_obs = unname(t_obs))
}

cat("Running wild cluster bootstrap (B =", B, ")...\n")
weekCamp$.lc  <- log(weekCamp$campaigns)
weekLabel$.lfe <- log(weekLabel$num_financial_emergency + 1)
weekLabel$.lbiz <- log(weekLabel$num_business + 1)
official <- weekLabel %>% filter((week >= 40 & year == "2020") | year == "2021")
official$.lfe <- log(official$num_financial_emergency + 1)

r_camp <- wcr_p(weekCamp,  ".lc",  controls = C1, B = B)
r_fe   <- wcr_p(weekLabel, ".lfe", controls = C2, B = B)
r_biz  <- wcr_p(weekLabel, ".lbiz",controls = C2, B = B)
r_d3   <- wcr_p(official,  ".lfe", controls = C2, B = B)

boot_tab <- data.frame(
  Specification = c("Log Campaigns (diff1)", "Fin. Emergency (diff2)",
                    "Business (diff2)", "Fin. Emerg. Post-Launch (diff3)"),
  Cluster_p   = c(r_camp$p_asym, r_fe$p_asym, r_biz$p_asym, r_d3$p_asym),
  WildBoot_p  = c(r_camp$p_boot, r_fe$p_boot, r_biz$p_boot, r_d3$p_boot)
)
print(boot_tab, digits = 4)

## write wild_bootstrap.tex (same layout as the pipeline placeholder) --------
fmt <- function(x) formatC(x, format = "f", digits = 4)
wb <- c(
  "% Generated by Code/replication/referee2_robustness_fix.R",
  "\\begingroup", "\\centering",
  "\\begin{tabular}{lcc}", "\\toprule",
  "Specification & Cluster $p$-value & Wild bootstrap $p$-value \\\\", "\\midrule",
  paste0(boot_tab$Specification, " & ", fmt(boot_tab$Cluster_p), " & ",
         fmt(boot_tab$WildBoot_p), " \\\\"),
  "\\bottomrule",
  paste0("\\multicolumn{3}{l}{\\footnotesize{Restricted (null-imposed) Rademacher ",
         "wild cluster bootstrap, ", B, " draws, clustered on state.}}"),
  "\\end{tabular}", "\\par\\endgroup"
)
writeLines(wb, file.path(tab_dir, "wild_bootstrap.tex"))
cat("Wrote wild_bootstrap.tex\n")

## ---- (M4) Honest DiD --------------------------------------------------------
cat("\nRunning HonestDiD...\n")
weekCamp_es <- weekCamp %>%
  filter(year == "2020", !is.na(fWeek), !is.na(fWeek1End)) %>%
  mutate(time2treat = as.integer(week) - as.integer(fWeek),
         post_boundary = as.integer(fWeek1End) - as.integer(fWeek)) %>%
  filter(time2treat >= -12, time2treat <= post_boundary)
es_total <- feols(log(campaigns) ~ i(time2treat, ref = -1) +
                    cases + initial_claims + insured_unemployment_rate +
                    continued_claims + puaIC | state + week,
                  cluster = ~state, weights = ~total_population, data = weekCamp_es)

honest_ok <- FALSE
honest_tab <- NULL
if (requireNamespace("HonestDiD", quietly = TRUE)) {
  res <- tryCatch({
    es_terms <- grep("^time2treat::", names(coef(es_total)), value = TRUE)
    es_lags  <- as.integer(gsub("^time2treat::", "", es_terms))
    ord <- order(es_lags); es_terms <- es_terms[ord]; es_lags <- es_lags[ord]
    betahat <- unname(coef(es_total)[es_terms])
    sigma   <- unname(vcov(es_total)[es_terms, es_terms, drop = FALSE])
    sigma   <- (sigma + t(sigma)) / 2
    keep <- !is.na(betahat)
    betahat <- betahat[keep]; sigma <- sigma[keep, keep, drop = FALSE]; es_lags <- es_lags[keep]
    HonestDiD::createSensitivityResults_relativeMagnitudes(
      betahat = betahat, sigma = sigma,
      numPrePeriods = sum(es_lags < 0), numPostPeriods = sum(es_lags >= 0),
      Mbarvec = c(0.5, 1, 1.5, 2))
  }, error = function(e) { cat("   HonestDiD error:", conditionMessage(e), "\n"); NULL })
  if (!is.null(res)) {
    honest_ok <- TRUE
    honest_tab <- data.frame(Mbar = res$Mbar, lb = res$lb, ub = res$ub)
    print(honest_tab, digits = 4)
    hd <- c("% Generated by Code/replication/referee2_robustness_fix.R",
            "\\begingroup", "\\centering", "\\begin{tabular}{rrr}", "\\toprule",
            "$\\bar{M}$ & Lower bound & Upper bound \\\\", "\\midrule",
            paste0(formatC(honest_tab$Mbar, format="f", digits=1), " & ",
                   formatC(honest_tab$lb, format="f", digits=4), " & ",
                   formatC(honest_tab$ub, format="f", digits=4), " \\\\"),
            "\\bottomrule",
            "\\multicolumn{3}{l}{\\footnotesize{Relative-magnitudes bounds (Rambachan-Roth 2023) on the event-study ATT.}}",
            "\\end{tabular}", "\\par\\endgroup")
    writeLines(hd, file.path(tab_dir, "honest_did.tex"))
    cat("Wrote honest_did.tex\n")
  }
}

## ---- emit the macro values to patch into inline_stats.tex ------------------
fmt_p <- function(p) if (is.na(p)) "??" else if (p < 0.001) "$<$0.001" else formatC(p, format="f", digits=3)
cat("\n==== MACRO VALUES ====\n")
cat("wildPFinEmerg =", fmt_p(r_fe$p_boot), "\n")
cat("wildPBusiness =", fmt_p(r_biz$p_boot), "\n")
if (honest_ok) {
  i1 <- which(honest_tab$Mbar == 1)
  cat("honestDidLowerMone =", formatC(honest_tab$lb[i1], format="f", digits=4), "\n")
  cat("honestDidUpperMone =", formatC(honest_tab$ub[i1], format="f", digits=4), "\n")
}
cat("======================\n")
